### ISSUE TITLE
Missing code :)

### ISSUE THREAD

**Issue by readingdancer** [Vizioz/FontAwesomeIconPack#1]
Hi @skttl ,

I came across your package on the OUR Umbraco site and it looked like it was going to do what I am looking for, which is to allow the Font Awesome icons to be used within the back office as icons for the document types, i.e. they would then show in the tree. However, from what I can see from your ZIP file, the package on OUR just installs the Font Awesome font, but no actual code to make this work? ( Unless it is meant to work magically :) )

I wondered if you did have this working in Umbraco 8, if so, it would be great to see the source code appear here, I'd be happy to contribute if it still needs a bit of work for V8.

Cheers, Chris

**Comment by skttl** [comment]
Hi Chris

It should work, as the package includes both fonts, css and a package.manifest.

All that is needed for adding icons is a css-file containing the icons, where their classes must start with `icon-`.

I'm pretty sure it will work on v8 too.
