### ISSUE TITLE
Font file path is incorrect

### ISSUE THREAD

**Issue by dallastaylor** [Vizioz/FontAwesomeIconPack#5]
After installing the package the icons were not displaying in the picker - only a square for each icon. 

We found the picker was loading font files from **/App_Plugins/FontAwesomeIconPack/fonts/fa-solid-900.ttf** but the font files were in the plugin root -**/App_Plugins/FontAwesomeIconPack/fa-solid-900.ttf**

We copied the font files into a font subdirectory to resolve the problem.

Umbraco version 7.15.5

**Comment by readingdancer** [comment]
Ah darn it, that must be an issue with the release I did last night with the new https://github.com/umbraco/UmbPack package. I will check it now and re-deploy ASAP. Thanks for raising the ticket.

**Comment by readingdancer** [comment]
This should now be fix and it has already been automatically deployed to the Our site :)

https://our.umbraco.com/packages/backoffice-extensions/fontawesome-icon-pack/
