### ISSUE TITLE
Not working in Umbraco v8.6.1

### ISSUE THREAD

**Issue by chrden** [Vizioz/FontAwesomeIconPack#7]
I installed the package within the CMS and, as per the instructions to test it, went to change the icon for a document type and filtered by 'umb' but all I can see are the standard icons provided by Umbraco 

I installed this in Umbraco 8.6.1

For good measure I restarted my site and recycled the app pool in IIS

Is there a step I'm missing?

![image](https://user-images.githubusercontent.com/22013176/83253135-60440380-a1a4-11ea-9a15-33080aff828f.png)
![image](https://user-images.githubusercontent.com/22013176/83253210-7fdb2c00-a1a4-11ea-96fc-431e7b114541.png)

**Comment by readingdancer** [comment]
Hi Chris,

That’s strange, I am just getting up over here in the USA, I’ll take a look shortly. 

Cheers, Chris

**Comment by RealGecko** [comment]
Hello,

[Manifest file](https://github.com/Vizioz/FontAwesomeIconPack/blob/a3d2e63beb704e991226a3850ec9f5362d645353/source/package.manifest) registers dependency to "font-awesome**5130**.css", but css file is now called "font-awesome.css". After changing the name to proper one, everything works just fine for me.

Cheers,

**Comment by readingdancer** [comment]
Yes @RealGecko is right, I changed the name of the CSS file and forgot to change it in the manifest file. I have just fixed this and have pushed a new version up onto Our Umbraco, @chrisdent14 please do let me know that the new version is working for you?

**Comment by readingdancer** [comment]
Fixed by: https://github.com/Vizioz/FontAwesomeIconPack/commit/efc4ef029e18e2417811b4141452cd16cb010d1d

**Comment by chrden** [comment]
@readingdancer Just installed the new version of the package and it is now working. Thanks for the quick fix and thanks @RealGecko for the response 👍
