### ISSUE TITLE
Add support for the free COVID-19 icons.

### ISSUE THREAD

**Issue by readingdancer** [Vizioz/FontAwesomeIconPack#8]
Font Awesome have a list of COVID-19 related icons, I think most of them are already included in the standard Font Awesome 5 icon list, but some are not, so we need to check if they exist and if not, we need to add the new ones. The list can be found here:

https://fontawesome.com/icons?d=gallery&q=covid-19&m=free

**Comment by MiguelLopez6** [comment]
Covid free icons added together with the update to 5.15.1
